# Generated by Django 5.0.14 on 2026-08-25 20:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('networks', '0002_initial'),
        ('nodes', '0002_initial'),
        ('organizations', '0001_initial'),
        ('storage', '0001_initial'),
        ('vm_templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('hostname', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('CREATING', 'Creating'), ('STOPPED', 'Stopped'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('SUSPENDED', 'Suspended'), ('MIGRATING', 'Migrating'), ('ERROR', 'Error'), ('DELETING', 'Deleting'), ('UNKNOWN', 'Unknown')], db_index=True, default='CREATING', max_length=20)),
                ('provisioning_state', models.CharField(choices=[('REQUESTED', 'Requested'), ('ALLOCATING', 'Allocating'), ('DISK_CREATED', 'Disk created'), ('NETWORK_CREATED', 'Network created'), ('DOMAIN_CREATED', 'Domain created'), ('CLOUD_INIT_ATTACHED', 'Cloud-init attached'), ('STARTED', 'Started'), ('READY', 'Ready'), ('ERROR', 'Error')], default='REQUESTED', max_length=30)),
                ('os_type', models.CharField(blank=True, default='linux', max_length=100)),
                ('firmware', models.CharField(choices=[('BIOS', 'BIOS'), ('UEFI', 'UEFI')], default='BIOS', max_length=10)),
                ('machine_type', models.CharField(default='q35', max_length=50)),
                ('cpu_count', models.PositiveIntegerField(default=1)),
                ('cpu_sockets', models.PositiveIntegerField(default=1)),
                ('cpu_cores', models.PositiveIntegerField(default=1)),
                ('cpu_threads', models.PositiveIntegerField(default=1)),
                ('cpu_model', models.CharField(default='host-passthrough', max_length=100)),
                ('memory_mb', models.PositiveIntegerField(default=2048)),
                ('min_memory_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('max_memory_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('ballooning_enabled', models.BooleanField(default=True)),
                ('boot_order', models.JSONField(blank=True, default=list, help_text='e.g. ["disk", "cdrom", "network"]')),
                ('autostart', models.BooleanField(default=False)),
                ('cloud_init_enabled', models.BooleanField(default=False)),
                ('cloud_init_config', models.JSONField(blank=True, default=dict)),
                ('domain_uuid', models.UUIDField(default=uuid.uuid4, help_text='The libvirt domain UUID -- distinct from our own `uuid` public id.', unique=True)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=255)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vms', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='virtual_machines', to='nodes.node')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_machines', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_machines', to='organizations.project')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vms', to='vm_templates.template')),
            ],
            options={
                'db_table': 'virtual_machines',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VMDisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('volume_id', models.CharField(blank=True, default='', help_text='Agent/storage-backend-assigned volume identifier or path.', max_length=255)),
                ('bus', models.CharField(choices=[('VIRTIO', 'VirtIO'), ('VIRTIO_SCSI', 'VirtIO SCSI'), ('SATA', 'SATA'), ('IDE', 'IDE')], default='VIRTIO', max_length=20)),
                ('device', models.CharField(blank=True, default='', help_text='e.g. vda, sdb', max_length=20)),
                ('size_bytes', models.BigIntegerField()),
                ('format', models.CharField(default='qcow2', max_length=10)),
                ('bootable', models.BooleanField(default=False)),
                ('readonly', models.BooleanField(default=False)),
                ('discard', models.BooleanField(default=True)),
                ('iothread', models.BooleanField(default=False)),
                ('boot_index', models.PositiveSmallIntegerField(default=0)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disks', to='storage.storagepool')),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disks', to='virtual_machines.virtualmachine')),
            ],
            options={
                'db_table': 'vm_disks',
                'ordering': ['boot_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='VMNic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('model', models.CharField(choices=[('VIRTIO', 'VirtIO'), ('E1000', 'E1000')], default='VIRTIO', max_length=10)),
                ('vlan', models.PositiveIntegerField(blank=True, null=True)),
                ('rate_limit_mbps', models.PositiveIntegerField(blank=True, null=True)),
                ('bootable', models.BooleanField(default=False)),
                ('boot_index', models.PositiveSmallIntegerField(default=0)),
                ('ip_address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nic', to='networks.ipaddress')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nics', to='networks.network')),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nics', to='virtual_machines.virtualmachine')),
            ],
            options={
                'db_table': 'vm_nics',
                'ordering': ['boot_index', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='virtualmachine',
            index=models.Index(fields=['organization', '-created_at'], name='virtual_mac_organiz_ef3b80_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualmachine',
            index=models.Index(fields=['node', 'status'], name='virtual_mac_node_id_fa5222_idx'),
        ),
        migrations.AddConstraint(
            model_name='virtualmachine',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_vm_name_per_project'),
        ),
        migrations.AddConstraint(
            model_name='virtualmachine',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('created_by', 'idempotency_key'), name='unique_vm_idempotency_key_per_user'),
        ),
    ]
