# Generated by Django 5.0.14 on 2026-09-02 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_initial'),
        ('virtual_machines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmdisk',
            name='source_image',
            field=models.ForeignKey(blank=True, help_text='Set when this disk was seeded from an image at creation time (e.g. deploying from a Template) -- provenance only; CREATE_DISK consumes it once and never re-reads it after.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disks_created_from', to='images.image'),
        ),
    ]
