# Generated by Django 5.0.14 on 2026-08-25 20:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('address', models.GenericIPAddressField()),
                ('state', models.CharField(choices=[('AVAILABLE', 'Available'), ('ALLOCATED', 'Allocated'), ('RESERVED', 'Reserved'), ('BLOCKED', 'Blocked')], db_index=True, default='AVAILABLE', max_length=10)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'ipam_addresses',
                'ordering': ['subnet_id', 'address'],
            },
        ),
        migrations.CreateModel(
            name='IPPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, default='default', max_length=100)),
                ('start_address', models.GenericIPAddressField()),
                ('end_address', models.GenericIPAddressField()),
            ],
            options={
                'db_table': 'ipam_pools',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('BRIDGE', 'Linux Bridge'), ('VLAN', 'VLAN'), ('NAT', 'NAT'), ('ROUTED', 'Routed'), ('ISOLATED', 'Isolated')], default='BRIDGE', max_length=10)),
                ('bridge', models.CharField(help_text='e.g. vmbr0', max_length=32)),
                ('vlan_id', models.PositiveIntegerField(blank=True, null=True)),
                ('dhcp_enabled', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ERROR', 'Error')], default='ACTIVE', max_length=10)),
            ],
            options={
                'db_table': 'networks',
                'ordering': ['node_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('cidr', models.CharField(help_text='e.g. 10.20.120.0/24', max_length=43)),
                ('gateway', models.GenericIPAddressField(blank=True, null=True)),
                ('dns_servers', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'ipam_subnets',
            },
        ),
    ]
