# Generated by Django 5.0.14 on 2026-08-25 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('networks', '0001_initial'),
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='nodes.node'),
        ),
        migrations.AddField(
            model_name='subnet',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subnets', to='networks.network'),
        ),
        migrations.AddField(
            model_name='ippool',
            name='subnet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='networks.subnet'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='subnet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='networks.subnet'),
        ),
        migrations.AlterUniqueTogether(
            name='network',
            unique_together={('node', 'bridge', 'vlan_id')},
        ),
        migrations.AlterUniqueTogether(
            name='subnet',
            unique_together={('network', 'cidr')},
        ),
        migrations.AlterUniqueTogether(
            name='ipaddress',
            unique_together={('subnet', 'address')},
        ),
    ]
