# Generated by Django 5.0.14 on 2026-08-25 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization', '-created_at'], name='events_organiz_7366ef_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['resource_type', 'resource_id'], name='events_resourc_8a964c_idx'),
        ),
    ]
