# Generated by Django 5.0.14 on 2026-08-25 20:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, default='', max_length=50)),
                ('type', models.CharField(choices=[('ISO', 'ISO'), ('QCOW2', 'QCOW2'), ('RAW', 'RAW'), ('VMDK', 'VMDK')], max_length=10)),
                ('format', models.CharField(blank=True, default='', max_length=10)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('checksum_algorithm', models.CharField(default='sha256', max_length=20)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('source', models.CharField(default='UPLOAD', max_length=20)),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending upload'), ('UPLOADING', 'Uploading'), ('VERIFYING', 'Verifying checksum'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='PENDING', max_length=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageUploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('total_size_bytes', models.BigIntegerField()),
                ('received_bytes', models.BigIntegerField(default=0)),
                ('next_chunk_index', models.PositiveIntegerField(default=0)),
                ('expected_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('UPLOADING', 'Uploading'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('ABORTED', 'Aborted')], default='UPLOADING', max_length=10)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'image_upload_sessions',
            },
        ),
    ]
