# Generated by Django 5.0.14 on 2026-08-25 20:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoragePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('DIRECTORY', 'Directory'), ('LVM', 'LVM'), ('LVM_THIN', 'LVM-thin'), ('ZFS', 'ZFS'), ('NFS', 'NFS'), ('CEPH_RBD', 'Ceph RBD')], max_length=20)),
                ('path', models.CharField(help_text='Mount point, volume group, dataset, or export path on the node.', max_length=500)),
                ('capacity_bytes', models.BigIntegerField(default=0)),
                ('used_bytes', models.BigIntegerField(default=0)),
                ('available_bytes', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='ONLINE', max_length=10)),
                ('shared', models.BooleanField(default=False, help_text='Visible/usable from more than one node -- required for migration.')),
                ('enabled', models.BooleanField(default=True)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_pools', to='nodes.node')),
            ],
            options={
                'db_table': 'storage_pools',
                'ordering': ['node_id', 'name'],
                'unique_together': {('node', 'name')},
            },
        ),
    ]
