# Generated by Django 5.0.14 on 2026-08-25 20:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('default_cpu_count', models.PositiveIntegerField(default=2)),
                ('default_memory_mb', models.PositiveIntegerField(default=4096)),
                ('default_disk_gb', models.PositiveIntegerField(default=20)),
                ('default_firmware', models.CharField(default='BIOS', max_length=10)),
                ('default_os_type', models.CharField(default='linux', max_length=100)),
                ('network_defaults', models.JSONField(blank=True, default=dict, help_text='e.g. {"model": "VIRTIO", "count": 1}')),
                ('cloud_init_defaults', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='images.image')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='organizations.organization')),
            ],
            options={
                'db_table': 'vm_templates',
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
