# Generated by Django 5.0.14 on 2026-08-25 20:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('CREATING', 'Creating'), ('READY', 'Ready'), ('DELETING', 'Deleting'), ('ROLLING_BACK', 'Rolling back'), ('ERROR', 'Error')], default='CREATING', max_length=15)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('agent_snapshot_id', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'snapshots',
                'ordering': ['-created_at'],
            },
        ),
    ]
