# Generated by Django 5.0.14 on 2026-08-25 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('snapshots', '0001_initial'),
        ('virtual_machines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='vm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='virtual_machines.virtualmachine'),
        ),
        migrations.AlterUniqueTogether(
            name='snapshot',
            unique_together={('vm', 'name')},
        ),
    ]
