# Generated by Django 5.0.14 on 2026-08-25 20:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('agent_id', models.UUIDField(default=None, null=True, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled'), ('REVOKED', 'Revoked'), ('OFFLINE', 'Offline')], default='ACTIVE', max_length=20)),
                ('token_hash', models.CharField(blank=True, db_index=True, default='', max_length=64, unique=True)),
                ('token_prefix', models.CharField(blank=True, default='', max_length=12)),
                ('certificate_fingerprint', models.CharField(blank=True, default='', max_length=128)),
                ('mtls_enabled', models.BooleanField(default=False)),
                ('protocol_version', models.CharField(default='1.0', max_length=16)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agents',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('hostname', models.CharField(max_length=255)),
                ('fqdn', models.CharField(blank=True, default='', max_length=255)),
                ('admin_state', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Maintenance'), ('DISABLED', 'Disabled')], default='ACTIVE', max_length=20)),
                ('agent_version', models.CharField(blank=True, default='', max_length=32)),
                ('kernel', models.CharField(blank=True, default='', max_length=128)),
                ('architecture', models.CharField(blank=True, default='', max_length=32)),
                ('cpu_model', models.CharField(blank=True, default='', max_length=255)),
                ('cpu_threads', models.PositiveIntegerField(default=0)),
                ('cpu_cores', models.PositiveIntegerField(default=0)),
                ('cpu_sockets', models.PositiveIntegerField(default=0)),
                ('memory_total_mb', models.PositiveBigIntegerField(default=0)),
                ('memory_available_mb', models.PositiveBigIntegerField(default=0)),
                ('storage_total_gb', models.PositiveBigIntegerField(default=0)),
                ('storage_available_gb', models.PositiveBigIntegerField(default=0)),
                ('reported_vm_count', models.PositiveIntegerField(default=0)),
                ('last_seen', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'nodes',
                'ordering': ['name'],
            },
        ),
    ]
