# Generated by Django 5.0.14 on 2026-08-25 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodes', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='agent',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='nodes.node'),
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('organization', 'hostname')},
        ),
    ]
