# Generated by Django 5.0.14 on 2026-08-25 20:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('VM_CREATE', 'Create VM'), ('VM_START', 'Start VM'), ('VM_STOP', 'Stop VM'), ('VM_SHUTDOWN', 'Shutdown VM'), ('VM_REBOOT', 'Reboot VM'), ('VM_RESET', 'Reset VM'), ('VM_PAUSE', 'Pause VM'), ('VM_RESUME', 'Resume VM'), ('VM_DELETE', 'Delete VM'), ('VM_CLONE', 'Clone VM'), ('VM_MIGRATE', 'Migrate VM'), ('DISK_CREATE', 'Create disk'), ('DISK_DELETE', 'Delete disk'), ('DISK_RESIZE', 'Resize disk'), ('DISK_ATTACH', 'Attach disk'), ('DISK_DETACH', 'Detach disk'), ('SNAPSHOT_CREATE', 'Create snapshot'), ('SNAPSHOT_DELETE', 'Delete snapshot'), ('SNAPSHOT_ROLLBACK', 'Roll back snapshot'), ('BACKUP_CREATE', 'Create backup'), ('BACKUP_RESTORE', 'Restore backup'), ('IMAGE_IMPORT', 'Import image'), ('WEBHOOK_DELIVERY', 'Deliver webhook')], max_length=50)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELING', 'Canceling'), ('CANCELED', 'Canceled')], db_index=True, default='QUEUED', max_length=20)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.CharField(blank=True, default='', max_length=64)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('message', models.CharField(blank=True, default='', max_length=500)),
                ('error', models.TextField(blank=True, default='')),
                ('logs', models.JSONField(blank=True, default=list)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('timeout_seconds', models.PositiveIntegerField(default=600)),
                ('retries', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
