# Generated by Django 5.0.14 on 2026-08-25 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('nodes', '0002_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='nodes.node'),
        ),
        migrations.AddField(
            model_name='job',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['resource_type', 'resource_id'], name='jobs_resourc_f8bc8a_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['organization', '-created_at'], name='jobs_organiz_d58d5b_idx'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('created_by', 'type', 'idempotency_key'), name='unique_job_idempotency_key_per_user_type'),
        ),
    ]
