# Generated by Django 5.0.14 on 2026-08-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('VM_CREATE', 'Create VM'), ('VM_START', 'Start VM'), ('VM_STOP', 'Stop VM'), ('VM_SHUTDOWN', 'Shutdown VM'), ('VM_REBOOT', 'Reboot VM'), ('VM_RESET', 'Reset VM'), ('VM_PAUSE', 'Pause VM'), ('VM_RESUME', 'Resume VM'), ('VM_DELETE', 'Delete VM'), ('VM_CLONE', 'Clone VM'), ('VM_MIGRATE', 'Migrate VM'), ('DISK_CREATE', 'Create disk'), ('DISK_DELETE', 'Delete disk'), ('DISK_RESIZE', 'Resize disk'), ('DISK_ATTACH', 'Attach disk'), ('DISK_DETACH', 'Detach disk'), ('NIC_ATTACH', 'Attach NIC'), ('NIC_DETACH', 'Detach NIC'), ('NETWORK_CREATE', 'Create network'), ('NETWORK_DELETE', 'Delete network'), ('SNAPSHOT_CREATE', 'Create snapshot'), ('SNAPSHOT_DELETE', 'Delete snapshot'), ('SNAPSHOT_ROLLBACK', 'Roll back snapshot'), ('BACKUP_CREATE', 'Create backup'), ('BACKUP_RESTORE', 'Restore backup'), ('IMAGE_IMPORT', 'Import image'), ('WEBHOOK_DELIVERY', 'Deliver webhook')], max_length=50),
        ),
    ]
