# Generated by Django 5.0.14 on 2026-08-25 20:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('FULL', 'Full'), ('INCREMENTAL', 'Incremental'), ('SNAPSHOT', 'Snapshot-based')], default='FULL', max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('VERIFYING', 'Verifying'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('RESTORING', 'Restoring'), ('DELETED', 'Deleted')], default='PENDING', max_length=10)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('encrypted', models.BooleanField(default=False)),
                ('agent_backup_ref', models.CharField(blank=True, default='', max_length=500)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('retention_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'backups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('backup_type', models.CharField(choices=[('FULL', 'Full'), ('INCREMENTAL', 'Incremental'), ('SNAPSHOT', 'Snapshot-based')], default='FULL', max_length=15)),
                ('cron_expression', models.CharField(help_text='Standard 5-field cron expression, evaluated in `timezone`.', max_length=100)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('retention_days', models.PositiveIntegerField(default=30)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'backup_schedules',
            },
        ),
        migrations.CreateModel(
            name='BackupTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('LOCAL', 'Local'), ('NFS', 'NFS'), ('S3', 'S3'), ('MINIO', 'MinIO'), ('CEPH', 'Ceph')], max_length=10)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Endpoint/bucket/path/credential-reference config for this target.')),
                ('encryption_key_id', models.CharField(blank=True, default='', help_text='Reference to an externally-managed key; NodePilot never stores raw key material.', max_length=255)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'backup_targets',
            },
        ),
    ]
