# Generated by Django 5.0.14 on 2026-08-25 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backups', '0001_initial'),
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('organizations', '0002_initial'),
        ('virtual_machines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='vm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='virtual_machines.virtualmachine'),
        ),
        migrations.AddField(
            model_name='backupschedule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_schedules', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='backupschedule',
            name='periodic_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='django_celery_beat.periodictask'),
        ),
        migrations.AddField(
            model_name='backupschedule',
            name='vm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_schedules', to='virtual_machines.virtualmachine'),
        ),
        migrations.AddField(
            model_name='backuptarget',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_targets', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='backupschedule',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='backups.backuptarget'),
        ),
        migrations.AddField(
            model_name='backup',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backups', to='backups.backuptarget'),
        ),
        migrations.AlterUniqueTogether(
            name='backuptarget',
            unique_together={('organization', 'name')},
        ),
    ]
