# Generated by Django 5.0.14 on 2026-08-29 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backuptarget',
            options={'ordering': ['name']},
        ),
    ]
