"""
The full RBAC permission catalog (section 7). This is the single source of
truth for valid codenames; `apps.permissions.models.Permission` rows are
seeded from this list by the `seed_rbac` management command, and role
policy checks always validate against it.
"""

PERMISSION_CATALOG: dict[str, str] = {
    "node.view": "View hypervisor nodes",
    "node.manage": "Register, update, and remove hypervisor nodes",
    "vm.view": "View virtual machines",
    "vm.create": "Create virtual machines",
    "vm.update": "Update virtual machine configuration",
    "vm.delete": "Delete virtual machines",
    "vm.start": "Start virtual machines",
    "vm.stop": "Stop virtual machines",
    "vm.reboot": "Reboot virtual machines",
    "vm.console": "Open the interactive VM console",
    "vm.snapshot": "Create, delete, and roll back VM snapshots",
    "vm.clone": "Clone virtual machines",
    "vm.migrate": "Migrate virtual machines between nodes",
    "storage.view": "View storage pools and volumes",
    "storage.manage": "Create and modify storage pools and volumes",
    "network.view": "View networks and IP allocations",
    "network.manage": "Create and modify networks and IP allocations",
    "image.view": "View the image/ISO library",
    "image.upload": "Upload images and ISOs",
    "image.delete": "Delete images and ISOs",
    "template.view": "View VM templates",
    "template.manage": "Create and modify VM templates",
    "backup.view": "View backups",
    "backup.create": "Create backups",
    "backup.restore": "Restore from a backup",
    "backup.delete": "Delete backups",
    "user.view": "View platform users",
    "user.manage": "Create, update, and remove platform users",
    "organization.manage": "Manage organizations, projects, memberships, and quotas",
    "audit.view": "View the audit log",
    "job.view": "View background jobs",
    "job.manage": "Cancel and retry background jobs",
    "webhook.manage": "Configure webhooks",
    "event.view": "View the event stream",
}

DEFAULT_ROLES: dict[str, list[str]] = {
    "Admin": list(PERMISSION_CATALOG.keys()),
    "Operator": [
        "node.view",
        "vm.view",
        "vm.create",
        "vm.update",
        "vm.delete",
        "vm.start",
        "vm.stop",
        "vm.reboot",
        "vm.console",
        "vm.snapshot",
        "vm.clone",
        "storage.view",
        "network.view",
        "network.manage",
        "image.view",
        "image.upload",
        "template.view",
        "backup.view",
        "backup.create",
        "backup.restore",
        "job.view",
        "job.manage",
        "event.view",
    ],
    "Viewer": [
        "node.view",
        "vm.view",
        "storage.view",
        "network.view",
        "image.view",
        "template.view",
        "backup.view",
        "job.view",
        "event.view",
    ],
}
